# Site settings
title: Friends of the Bloomingdale Trail
email: paul@bloomingdaletrail.org
description: >
    Friends of the Bloomingdale Trail is a not-for-profit all-volunteer
    grassroots organization advocating and organizing for Chicago’s next great park, The 606
    and The Bloomingdale Trail, a 2-3/4 mile elevated multi-use park.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bloomingdaletrail.org" # the base hostname & protocol for your site
twitter_username: thebloomingdale
google_api_key: AIzaSyCAIVMKDMR7WcybZfsTYWqoTrws3LtqGjU

# Build settings
markdown: kramdown

# Gallery (ReFraming Ruin) settings
gallery_data_name: reframing_ruin

defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            fixednav: true

exclude:
    - vendor
    - Makefile
    - Gemfile
    - Gemfile.lock
    - README.md
    - TODO
    - cf-invalidate.json
    - pdf
